### ISSUE TITLE
metodologia altamente contestavel

### ISSUE THREAD

**Issue by seijiakiyama** [bgaraujo/MetodoChang#1]
gostaria de deixar claro aqui que o sr. bruno nao tem vivencia em pastelaria para descrever o funcionamento de uma, muito menos de basear toda uma metodologia nisso. obrigado.

**Comment by bgaraujo** [comment]
o q te falta é experiencia com o hashi e paz no coração

**Comment by seijiakiyama** [comment]
o que te falta é ódio
